In [1]:
import os

print("Current notebook directory:")
print(os.getcwd())

print("\nFiles one level above:")
print(os.listdir(".."))

Current notebook directory:
/Users/rishusingh/CASEFILE_MISSING_PERSON

Files one level above:
['Rishu_Singh_Resume (1).docx', 'Machine Learning', '.Rhistory', '.config', '.junie', 'Music', ' Deep Learning Practice', '.cursor', '.zprofile.pysave', 'MLAnkitamaam.ipynb', '.condarc', 'Exercises.ipynb', '.docker', '.copilot', '.gemini', '.mysqlsh-wb', 'Cisco Packet Tracer 9.0.1', 'reviews.csv', '.th-client', '.DS_Store', 'nltk_data', '.vscode-shared', '.CFUserTextEncoding', 'S37 - dataset.zip', '.xonshrc', 'train_model.py', 'preprocess.py', 'Data Visualization', 'Untitled.ipynb', '.zshrc', '.packettracer', 'dataset', '.arduinoIDE', '.streamlit', '.local', 'Pictures', '.zprofile', 'predict.py', 'Virtual Data Science with Python Trainee', '.claude', 'AI Startup Predictor', '.zsh_history', 'features.py', '.ipython', 'best_model.joblib', 'Desktop', 'Library', '.matplotlib', 'models', 'Matplotlib and Seaborn', '.lesshst', 'feature_builder.joblib', 'dataset 2', 'Sales & Demand Forecasting for Businesses', 'README.md', 'VoiceShield', '.node_repl_history', '.android', 'untitled.txt', '.mamba', 'PBL_REPORT_FORMAT_AUTUMN_2026-27 (1).pages', '.codex', 'Public', 'generate_data.py', '.idlerc', '.tcshrc', 'Numpy.ipynb', '.RData', '.virtual_documents', 'internship', '.anaconda', 'NLP', 'Multi-agent-research-system', 'Movies', '.gradle', '.Rapp.history', 'Logistics_Supply_Chain_Analysis', 'Movie Recommender System', 'Week1_Logistics_Supply_Chain_Analysis', '.Trash', 'CASEFILE_MISSING_PERSON', '.gradio', '.ipynb_checkpoints', '.jupyter', '.keras', 'Python practice', '.npm', 'Documents', 'venv', 'Deep Learning', 'Practice Ml', '.mysql_history', '.git', 'Arrays.ipynb', '.claude.json', '.vscode', '.arduino-create', '.bash_profile', 'data', 'Downloads', '.continuum', '.cache', '.gitconfig', '.ai-navigator', 'Mental Health Predictor', '.cufflinks', 'array_indexing.ipynb', '.ollama', '.viminfo', '.zsh_sessions', 'Pandas', 'ai-startup-success-predictor', '.conda', 'Stastics', 'AI Startup Success Predictor using Machine Learning']

In [2]:
print(
    "data folder exists:",
    os.path.exists("../data")
)

print(
    "synthetic folder exists:",
    os.path.exists("../data/synthetic")
)

data folder exists: True
synthetic folder exists: False

In [3]:
os.makedirs(
    "../data/synthetic",
    exist_ok=True
)

print("Synthetic folder created!")

Synthetic folder created!

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/gps_anomalies.csv"
)

df["timestamp"] = pd.to_datetime(
    df["timestamp"]
)

print("GPS data loaded:", df.shape)

GPS data loaded: (24730077, 23)

In [5]:
valid_data = df[
    df["cluster"] != -1
].copy()

print(
    "Valid records:",
    len(valid_data)
)

Valid records: 24730077

In [6]:
np.random.seed(42)

cases = []

for i in range(100):

    record = valid_data.sample(
        1,
        random_state=42 + i
    ).iloc[0]

    case_time = pd.to_datetime(
        record["timestamp"]
    )

    case = {
        "Case_ID": f"MP-2026-{i+1:03d}",
        "Person_ID": f"P{i+1:03d}",

        "Age_Group": np.random.choice([
            "18-25",
            "26-35",
            "36-45",
            "46-60"
        ]),

        "Gender": np.random.choice([
            "Male",
            "Female",
            "Not Specified"
        ]),

        "Last_Latitude":
            record["latitude"],

        "Last_Longitude":
            record["longitude"],

        "Last_Seen_Time":
            case_time,

        "Day":
            case_time.day_name(),

        "Weather": np.random.choice([
            "Clear",
            "Cloudy",
            "Rain"
        ]),

        "Usual_Area":
            record["cluster"],

        "Average_Distance":
            record["distance_km"],

        "Average_Speed":
            record["speed_kmh"],

        "Previous_Area":
            record["cluster"],

        "Time_Since_Last_Seen":
            np.random.choice([
                1, 2, 3, 4, 6, 8
            ]),

        "Target_Area":
            record["cluster"]
    }

    cases.append(case)

In [7]:
synthetic_cases = pd.DataFrame(
    cases
)

print(
    "Synthetic dataset shape:",
    synthetic_cases.shape
)

synthetic_cases.head()

Synthetic dataset shape: (100, 15)

,Case_ID,Person_ID,Age_Group,Gender,Last_Latitude,Last_Longitude,Last_Seen_Time,Day,Weather,Usual_Area,Average_Distance,Average_Speed,Previous_Area,Time_Since_Last_Seen,Target_Area
0,MP-2026-001,P001,36-45,Male,39.980525,116.449440,2008-10-12 08:38:24,Sunday,Rain,9,0.003579,6.441649,9,3,9
1,MP-2026-002,P002,46-60,Male,39.968322,116.421253,2009-06-04 06:21:42,Thursday,Clear,9,0.010934,39.361368,9,2,9
2,MP-2026-003,P003,36-45,Not Specified,40.024186,116.435575,2011-12-26 08:38:20,Monday,Rain,9,0.000613,2.205271,9,3,9
3,MP-2026-004,P004,46-60,Male,37.914902,112.147270,2009-01-27 05:59:54,Tuesday,Rain,6,0.039915,35.923149,6,8,6
4,MP-2026-005,P005,18-25,Female,39.981445,116.326191,2009-09-18 19:17:36,Friday,Cloudy,9,0.000949,1.707791,9,8,9

In [8]:
import os

os.makedirs(
    "../data/synthetic",
    exist_ok=True
)

In [9]:
synthetic_cases.to_csv(
    "../data/synthetic/missing_person_cases.csv",
    index=False
)

print(
    "Synthetic case dataset saved successfully!"
)

Synthetic case dataset saved successfully!

In [10]:
print(
    os.path.exists(
        "../data/synthetic/missing_person_cases.csv"
    )
)

True

In [11]:
cases = pd.read_csv(
    "../data/synthetic/missing_person_cases.csv"
)

print(cases.shape)
display(cases.head())

(100, 15)

,Case_ID,Person_ID,Age_Group,Gender,Last_Latitude,Last_Longitude,Last_Seen_Time,Day,Weather,Usual_Area,Average_Distance,Average_Speed,Previous_Area,Time_Since_Last_Seen,Target_Area
0,MP-2026-001,P001,36-45,Male,39.980525,116.449440,2008-10-12 08:38:24,Sunday,Rain,9,0.003579,6.441649,9,3,9
1,MP-2026-002,P002,46-60,Male,39.968322,116.421253,2009-06-04 06:21:42,Thursday,Clear,9,0.010934,39.361368,9,2,9
2,MP-2026-003,P003,36-45,Not Specified,40.024186,116.435575,2011-12-26 08:38:20,Monday,Rain,9,0.000613,2.205271,9,3,9
3,MP-2026-004,P004,46-60,Male,37.914902,112.147270,2009-01-27 05:59:54,Tuesday,Rain,6,0.039915,35.923149,6,8,6
4,MP-2026-005,P005,18-25,Female,39.981445,116.326191,2009-09-18 19:17:36,Friday,Cloudy,9,0.000949,1.707791,9,8,9

In [12]:
cases = pd.read_csv(
    "../data/synthetic/missing_person_cases.csv"
)

In [13]:
cases = pd.read_csv(
    "../data/synthetic/missing_person_cases.csv"
)

print("Dataset shape:", cases.shape)

cases.head()

Dataset shape: (100, 15)

,Case_ID,Person_ID,Age_Group,Gender,Last_Latitude,Last_Longitude,Last_Seen_Time,Day,Weather,Usual_Area,Average_Distance,Average_Speed,Previous_Area,Time_Since_Last_Seen,Target_Area
0,MP-2026-001,P001,36-45,Male,39.980525,116.449440,2008-10-12 08:38:24,Sunday,Rain,9,0.003579,6.441649,9,3,9
1,MP-2026-002,P002,46-60,Male,39.968322,116.421253,2009-06-04 06:21:42,Thursday,Clear,9,0.010934,39.361368,9,2,9
2,MP-2026-003,P003,36-45,Not Specified,40.024186,116.435575,2011-12-26 08:38:20,Monday,Rain,9,0.000613,2.205271,9,3,9
3,MP-2026-004,P004,46-60,Male,37.914902,112.147270,2009-01-27 05:59:54,Tuesday,Rain,6,0.039915,35.923149,6,8,6
4,MP-2026-005,P005,18-25,Female,39.981445,116.326191,2009-09-18 19:17:36,Friday,Cloudy,9,0.000949,1.707791,9,8,9